version: '3.8'
services:
  gateway:
    build: ./gateway
    image: gateway_image
    container_name: shareIt-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: server_image
    container_name: shareIt-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: postgresql
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root